#!/usr/bin/env python3
"""Generate the reviewed static Australian public-holiday dataset.

Run only during development. The browser app has no Python dependency.
"""
from __future__ import annotations

import json
from datetime import date, datetime, timezone
from pathlib import Path

import holidays

FY_MIN = 2020
FY_MAX = 2035
STATES = ("ACT", "NSW", "NT", "QLD", "SA", "TAS", "VIC", "WA")
DATA_DIR = Path(__file__).resolve().parents[1] / "data"
OUT = DATA_DIR / "holidays.json"
JS_OUT = DATA_DIR / "holidays.js"


def main() -> None:
    lower = date(FY_MIN, 7, 1)
    upper = date(FY_MAX + 1, 6, 30)
    result: dict[str, object] = {
        "metadata": {
            "source": "python-holidays",
            "version": holidays.__version__,
            "generatedAt": datetime.now(timezone.utc).date().isoformat(),
            "fyStartYearMin": FY_MIN,
            "fyStartYearMax": FY_MAX,
            "rangeStart": lower.isoformat(),
            "rangeEnd": upper.isoformat(),
            "observed": True,
            "notes": "NSW Bank Holiday is excluded because it is not a general public holiday.",
        },
        "states": {},
    }
    states = result["states"]
    assert isinstance(states, dict)
    for state in STATES:
        calendar = holidays.Australia(
            years=range(lower.year, upper.year + 1), subdiv=state, observed=True
        )
        rows: dict[str, str] = {}
        for holiday_date, name in sorted(calendar.items()):
            if not lower <= holiday_date <= upper:
                continue
            if state == "NSW" and "bank holiday" in name.casefold():
                continue
            rows[holiday_date.isoformat()] = name
        states[state] = rows
    compact = json.dumps(result, ensure_ascii=False, separators=(",", ":"))
    OUT.write_text(compact + "\n", encoding="utf-8")
    JS_OUT.write_text(
        "// Generated by scripts/generate_holidays.py; do not edit.\n"
        f"export const HOLIDAY_DATA = {compact};\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT} and {JS_OUT} ({OUT.stat().st_size} bytes JSON)")


if __name__ == "__main__":
    main()
